# Generated by Django 3.1.7 on 2021-04-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_blogs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
